apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: le999/appp1:latest
        ports:
        - containerPort: 3000
        env:
          - name: VALIDATOR_URL
            value: tcp://sawtooth-org0peer0:4004

          - name: RETHINK_HOST
            value: rethinkdborg0-rethinkdb-proxy           
          - name: RETHINK_PORT
            value: "28015"   
          - name: RETHINK_PASSWORD
            value: rethinkdb   
          - name: RETHINK_USER
            value: admin
          - name: DB_NAME
            value: supply_chain

          - name: PRIVATE_KEY
            value: "1111111111111111111111111111111111111111111111111111111111111111"
          - name: JWT_SECRET
            value: shhhhh
          
          - name: SERVER
            value: http://localhost:3000
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: ClusterIP
  selector:
    app: myapp 
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-lb
# spec:
#   selector:
#     app: myapp
#   type: LoadBalancer
#   ports:
#     - name: "3000"
#       port: 3000
#       nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ledger-sync
  labels:
    app: ledger-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-sync
  template:
    metadata:
      labels:
        app: ledger-sync
    spec:
      containers:
      - name: ledger-sync
        image: le999/ledger_sync:latest
        env:
          - name: VALIDATOR_URL
            value: tcp://sawtooth-org0peer0:4004
          - name: RETRY_WAIT
            value: "5000"

          - name: RETHINK_HOST
            value: rethinkdborg0-rethinkdb-proxy          
          - name: RETHINK_PORT
            value: "28015"  
          - name: RETHINK_PASSWORD
            value: rethinkdb   
          - name: RETHINK_USER
            value: admin
          - name: DB_NAME
            value: supply_chain
